// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bibiejdxrizsrhiuefju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpYmllamR4cml6c3JoaXVlZmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDExNzUsImV4cCI6MjA2NTU3NzE3NX0.aFKItyu0QrERxI2pJF_L-jUHKvR0oDvqfVW0o-4Wt9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);